name: Web Development Bootcamp
run-name: Learning by Doing
on:
  push:
    paths:
      - 'prod/**'
      
jobs:
  Deploy-to-Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: curl -X POST -d api_key=${{ secrets.API_KEY }} -d environment=production -d sha=${{ github.sha }} https://staging.sleuth.io/api/1/deployments/king-julian/webdev/register_deploy
