name: Web Development Bootcamp
run-name: Learning by Doing
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy to:"
        required: True
        default: "staging"
        type: environment
        options:
          - production
          - staging
      
jobs:
  Deploy-to-Environment:
    runs-on: ubuntu-latest
    environment: $ENVIRONMENT
    steps:
      - run: curl -X POST -d api_key=${{ secrets.API_KEY }} -d environment=$ENVIRONMENT -d sha=${{ github.sha }} https://staging.sleuth.io/api/1/deployments/king-julian/webdev/register_deploy
        env:
          ENVIRONMENT: ${{ inputs.environment }}
